# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20161017_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubeuser',
            name='nickname',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubeuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
